name: Generate Snake

on:
  schedule:
    # This runs every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch: # Allows you to run it manually
  push:
    branches:
    - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # Generates the snake animation
# Generates the snake animation
      - name: generate-snake-game-from-github-contribution-grid
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg?palette=github-light&color_snake=#FF69B4&color_dots=#ebedf0,#f1f8ff,#ffb6c1,#ff69b4,#ff1493
            dist/github-snake-dark.svg?palette=github-dark&color_snake=#FF69B4&color_dots=#161b22,#6b1c3d,#b53d6b,#ff69b4,#ff1493

      # Pushes the generated files to a special branch called "output"
      - name: push github-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
